# Generated by Django 2.1 on 2018-08-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SLEEP', 'SLEEP')], max_length=64)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_bot.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('payment_id', models.CharField(max_length=255, null=True)),
                ('additional_info', models.TextField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_bot.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED'), ('COMPLETED', 'COMPLETED')], max_length=60)),
                ('payment_code', models.CharField(max_length=10, null=True)),
                ('payment_value', models.DecimalField(decimal_places=4, max_digits=28, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('WECHAT', 'WECHAT')], max_length=64, null=True)),
                ('item_type', models.CharField(choices=[('ONE_WEEK', 'ONE_WEEK'), ('ONE_MONTH', 'ONE_MONTH'), ('THREE_MONTH', 'THREE_MONTH')], max_length=64, null=True)),
                ('comment', models.TextField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_bot.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='VPN_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('expire_on', models.DateTimeField()),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=64)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_bot.Order')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_bot.Order'),
        ),
    ]
