# Generated by Django 2.1 on 2018-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code_issued_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
